# Generated by Django 3.2.8 on 2024-10-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='ast_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
