# Generated by Django 3.2.8 on 2024-10-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_alter_rule_ast_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
